debug:
	@echo "launching an example query for 'how to conquer the world'"
	ipython launch_query.py -- --query "conquer world"

alternative_splicing:
	python launch_query.py --query 'alternative splicing'
