idebug:
	@echo "launching an example query for 'how to conquer the world'"
	ipython launch_query.py -- --query "conquer world" -d
debug:
	@echo "launching an example query for 'how to conquer the world'"
	python launch_query.py --query "conquer world" -d

genetics:
	python genetics.py

debug:
	python launch_query.py -- --query "Natural selection on functional modules, a genome wide analysis" -d

alternative_splicing:
	python launch_query.py --query 'alternative splicing'
